### ISSUE TITLE
What the mean of "bin_path" in "params. py" ?

### ISSUE THREAD

**Issue by byxiaobai** [ocxtal/adaptivebandbench#1]
![image](https://user-images.githubusercontent.com/26520933/217735131-773b6bc2-b52c-4f4b-a552-3be423b673bc.png)
I'm trying to reproduce the experiment，but I don't know what I should write in the "bin_path".

**Comment by ocxtal** [comment]
sorry for slow response. here's explanation:

* the `bin_path` points to the directory where binaries for the benchmark were located.
  * the hardcoded path, `/home/suzukihajime/src/rognes`, is the directory of this repository on my local env, and additional `bin` is the directory the makefile creates for benchmark binaries. so when you clone this repository to your `$HOME/where/you/cloned/this/repo`, the `bin_path` should be `$HOME/where/you/cloned/this/repo/bin`.

and important thing that I've missed to note in the README:

* the current master has lots of changes after the benchmark was taken. and the benchmarking/plotting scripts under `scripts/` are outdated for the C++ codes in the current master.
  * could you try https://github.com/ocxtal/adaptivebandbench/tree/the-commit-that-i-took-benchmarks-for-the-preprint for reproducing the benchmark that I (we) put in the preprint on bioRxiv.

If you have further questions when reproducing the experiment, please ask me again.

**Comment by byxiaobai** [comment]
I really appreciate your help.
